<!DOCTYPE html>
<html lang="es">
<head>
    <title>AdminLTE 3 | Starter</title>
    <?
    require __DIR__ . '/../../admin-lte/style.phtml'; ?>
    <link rel="stylesheet" href="http://cdn.datatables.net/1.10.24/css/jquery.dataTables.min.css">
</head>
<body class="hold-transition sidebar-mini">
<div class="wrapper">

    <!-- Navbar -->
    <?
    require __DIR__ . '/../nav.phtml'; ?>
    <!-- /.navbar -->

    <!-- Main Sidebar Container -->
    <?
    require __DIR__ . '/../aside.phtml'; ?>
    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <?
        require __DIR__ . '/../header.phtml'; ?>
        <!-- /.content-header -->

        <!-- Main content -->
        <div class="content">
            <div class="container-fluid">
                <div class="row">
                    <div class="col">
                        <div class="card">
                            <div class="card-body">
                                <table id="usuarios" class="table table-flush display responsive nowrap" style="width:100%">
                                    <thead>
                                    <tr>
                                        <th>ID</th>
                                        <th>Tipo Identificación</th>
                                        <th>Itentificación</th>
                                        <th>Nombres</th>
                                        <th>Apellido Pat.</th>
                                        <th>Apellido Mat.</th>
                                        <th>Acciones</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- /.row -->
            </div><!-- /.container-fluid -->
        </div>
        <!-- /.content -->
    </div>
    <!-- /.content-wrapper -->

    <!-- Main Footer -->
    <?
    require __DIR__ . '/../footer.phtml'; ?>
</div>

<?
require __DIR__ . '/../../admin-lte/script.phtml'; ?>
<script src="https://cdn.jsdelivr.net/npm/datatables.net@1.10.24/js/jquery.dataTables.min.js"
        integrity="sha256-itm1F+qFhcjfGnrv+v18AA+Fa7sA8rQIT7J0YenNH64=" crossorigin="anonymous"></script>
<script>
    document.addEventListener("DOMContentLoaded", function (event) {
        console.log("DOM fully loaded and parsed");
    });
    $(document).ready(function () {
        $('#usuarios').DataTable({
            "language": {
                "url": "/datatables/config"
            },
            "responsive": true,
            "processing": true,
            "serverSide": true,
            "ajax": "/administrador/usuario/dt_usuarios"
        });
    });
</script>
</body>
</html>