<form action="/login" method="post">
    <div class="input-group mb-3">
        <input type="text" name="identificacion" class="form-control" placeholder="Identificación">
        <div class="input-group-append">
            <div class="input-group-text">
                <span class="fas fa-id-card-alt"></span>
            </div>
        </div>
    </div>
    <div class="input-group mb-3">
        <input type="password" name="password" class="form-control" placeholder="Contraseña">
        <div class="input-group-append">
            <div class="input-group-text">
                <span class="fas fa-lock"></span>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-7">
            <div class="icheck-primary">
                <input type="checkbox" id="remember" name="recuerdame">
                <label for="remember">
                    Recuérdame
                </label>
            </div>
        </div>
        <!-- /.col -->
        <div class="col-5">
            <button type="submit" class="btn btn-primary btn-block">Registrarse</button>
        </div>
        <!-- /.col -->
    </div>
</form>