<aside class="main-sidebar sidebar-light-info elevation-4">
    <!-- Brand Logo -->
    <a href="/" class="brand-link">
        <img src="/logo_unajma.png" alt="AdminLTE Logo"
             class="brand-image" style="opacity: .8">
        <span class="brand-text font-weight-light">Escalafón</span>
    </a>

    <!-- Sidebar -->
    <div class="sidebar">
        <!-- Sidebar user panel (optional) -->
        <div class="user-panel mt-3 pb-3 mb-3 d-flex">
            <div class="image">
                <img src="https://cdn.jsdelivr.net/npm/admin-lte@3.1.0/dist/img/user2-160x160.jpg" class="img-circle elevation-2"
                     alt="User Image">
            </div>
            <div class="info">
                <a href="#" class="d-block"><?= $_SESSION['nombres'] ?? null ?></a>
            </div>
        </div>

        <!-- SidebarSearch Form -->
        <div class="form-inline">
            <div class="input-group" data-widget="sidebar-search">
                <input class="form-control form-control-sidebar" type="search" placeholder="Search" aria-label="Search">
                <div class="input-group-append">
                    <button class="btn btn-sidebar">
                        <i class="fas fa-search fa-fw"></i>
                    </button>
                </div>
            </div>
        </div>

        <!-- Sidebar Menu -->
        <nav class="mt-2">
            <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
                <?
                foreach ($this->nav as $nav): ?>
                    <li class="nav-item <?= $nav['menu_open'] ?? null ?>">
                        <div class="btn text-left nav-link <?= $nav['active'] ?? null ?>">
                            <?= $nav['icon'] ?? null ?>
                            <p>
                                <?= $nav['name'] ?? null ?>
                                <i class="right fas fa-angle-left"></i>
                            </p>
                        </div>
                        <ul class="nav nav-treeview">
                            <? foreach ($nav['menu'] as $menu): ?>
                                <li class="nav-item">
                                    <a href="<?= $menu['link'] ?? null ?>" class="nav-link <?= $menu['active'] ?? null ?>">
                                        <i class="far fa-circle nav-icon"></i>
                                        <p><?= $menu['name'] ?? null ?></p>
                                    </a>
                                </li>
                            <?
                            endforeach; ?>
                        </ul>
                    </li>
                <?
                endforeach; ?>
            </ul>
        </nav>
        <!-- /.sidebar-menu -->
    </div>
    <!-- /.sidebar -->
</aside>