<div class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1 class="m-0"><?= $this->title ?? null ?></h1>
            </div><!-- /.col -->
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <?
                    foreach ($this->buttons as $button): ?>
                        <li class="breadcrumb-item">
                            <a type="button" class="btn <?= $button['class'] ?>">
                                <?= $button['icon'] ?>
                                <?= $button['name'] ?>
                            </a>
                        </li>
                    <?
                    endforeach; ?>
                </ol>
            </div><!-- /.col -->
        </div>
    </div><!-- /.container-fluid -->
</div>