<!DOCTYPE html>
<html lang="es">
<head>
    <?
    require __DIR__ . '/head/index.phtml' ?>
    <?
    require __DIR__ . '/../admin-lte/style.phtml'; ?>
</head>
<body class="hold-transition sidebar-mini">
<div class="wrapper">

    <!-- Navbar -->
    <?
    require __DIR__ . '/nav.phtml'; ?>
    <!-- /.navbar -->

    <!-- Main Sidebar Container -->
    <?
    require __DIR__ . '/aside.phtml'; ?>
    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <?
        require __DIR__ . '/header.phtml'; ?>
        <!-- /.content-header -->

        <!-- Main content -->
        <div class="content">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-lg-3 col-6">
                        <!-- small box -->
                        <div class="small-box bg-info">
                            <div class="inner">
                                <h3>150</h3>

                                <p>Usuarios</p>
                            </div>
                            <div class="icon">
                                <i class="fas fa-user-plus"></i>
                            </div>
                            <a href="/administrador/usuario" class="small-box-footer">Más información <i class="fas
                            fa-arrow-circle-right"></i></a>
                        </div>
                    </div>
                </div>
                <!-- /.row -->
            </div><!-- /.container-fluid -->
        </div>
        <!-- /.content -->
    </div>
    <!-- /.content-wrapper -->

    <!-- Main Footer -->
    <?
    require __DIR__ . '/footer.phtml'; ?>
</div>

<?
require __DIR__ . '/../admin-lte/script.phtml'; ?>
</body>
</html>