<!DOCTYPE html>
<html lang="es">
<head>
    <title>AdminLTE 3 | Starter</title>
    <?
    require __DIR__ . '/../admin-lte/style.phtml'; ?>
</head>
<body class="hold-transition sidebar-mini">
<div class="wrapper">

    <!-- Navbar -->
    <?
    require __DIR__ . '/nav.phtml'; ?>
    <!-- /.navbar -->

    <!-- Main Sidebar Container -->
    <?
    require __DIR__ . '/aside.phtml'; ?>
    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <div class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6">
                        <h1 class="m-0">Starter Page</h1>
                    </div><!-- /.col -->
                    <div class="col-sm-6">
                        <ol class="breadcrumb float-sm-right">
                            <li class="breadcrumb-item"><a href="#">Home</a></li>
                            <li class="breadcrumb-item active">Starter Page</li>
                        </ol>
                    </div><!-- /.col -->
                </div><!-- /.row -->
            </div><!-- /.container-fluid -->
        </div>
        <!-- /.content-header -->

        <!-- Main content -->
        <div class="content">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-lg-6">
                        <div class="card">
                            <div class="card-body">
                                <h5 class="card-title">title</h5>

                                <p class="card-text">
                                    Lorem ipsum dolor sit amet, consectetur adipisicing elit.
                                </p>

                                <a href="#" class="card-link">Card link</a>
                                <a href="#" class="card-link">Another link</a>
                            </div>
                        </div>

                    </div>
                </div>
                <!-- /.row -->
            </div><!-- /.container-fluid -->
        </div>
        <!-- /.content -->
    </div>
    <!-- /.content-wrapper -->

    <!-- Main Footer -->
    <?
    require __DIR__ . '/footer.phtml'; ?>
</div>

<?
require __DIR__ . '/../admin-lte/script.phtml'; ?>
</body>
</html>
