#!/usr/bin/env php
<?php
require __DIR__.'/../vendor/autoload.php';

use Symfony\Component\Console\Application;

$application = new Application();

$application->add(new \DataBase\Migrations\Index());
$application->add(new \DataBase\Seeders\Index());

$application->run();
