<!DOCTYPE html>
<html lang="en">
<head>
    <title>UNAJMA: Escalafón</title>
    <link rel="icon" href="/logo_unajma.png">
    <?
    require __DIR__ . '/../admin-lte/style.phtml' ?>
</head>
<body class="hold-transition login-page">
<div class="login-box">
    <!-- /.login-logo -->
    <div class="card card-outline card-primary">
        <div class="card-header text-center">
            <img src="/logo_unajma.png" alt="AdminLTE Logo"
                 class="img-responsive" style="opacity: .8;width: 50px">
        </div>
        <div class="card-body">
            <p class="login-box-msg">Regístrese para iniciar su sesión</p>

            <form action="/" method="post">
                <div class="input-group mb-3">
                    <input type="email" class="form-control" placeholder="Correo">
                    <div class="input-group-append">
                        <div class="input-group-text">
                            <span class="fas fa-envelope"></span>
                        </div>
                    </div>
                </div>
                <div class="input-group mb-3">
                    <input type="password" class="form-control" placeholder="Contraseña">
                    <div class="input-group-append">
                        <div class="input-group-text">
                            <span class="fas fa-lock"></span>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-7">
                        <div class="icheck-primary">
                            <input type="checkbox" id="remember">
                            <label for="remember">
                                Recuérdame
                            </label>
                        </div>
                    </div>
                    <!-- /.col -->
                    <div class="col-5">
                        <button type="submit" class="btn btn-primary btn-block">Registrarse</button>
                    </div>
                    <!-- /.col -->
                </div>
            </form>


            <p class="mb-1">
                <a href="forgot-password.html">Olvidé mi contraseña</a>
            </p>
        </div>
        <!-- /.card-body -->
    </div>
    <!-- /.card -->
</div>
<!-- /.login-box -->

<?
require __DIR__ . '/../admin-lte/script.phtml' ?>
</body>
</html>
