<!DOCTYPE html>
<html lang="en">
<head>
    <title>UNAJMA: Escalafón Login</title>
    <link rel="icon" href="/logo_unajma.png">
    <?
    require __DIR__ . '/../admin-lte/style.phtml' ?>
</head>
<body class="hold-transition login-page">
<div class="login-box">
    <!-- /.login-logo -->
    <div class="card card-outline card-primary">
        <div class="card-header text-center">
            <h1>ESACALAFÓN</h1>
            <img src="/logo_unajma.png" alt="AdminLTE Logo"
                 class="img-responsive" style="opacity: .8;width: 50px">
        </div>
        <div class="card-body">
            <p class="login-box-msg text-danger">Usuario o Contraña incorrectos</p>
    
            <?
            require __DIR__ . '/form/login.phtml' ?>

            <p class="mb-1">
                <a href="forgot-password">Olvidé mi contraseña</a>
            </p>
        </div>
        <!-- /.card-body -->
    </div>
    <!-- /.card -->
</div>
<!-- /.login-box -->

<?
require __DIR__ . '/../admin-lte/script.phtml' ?>
</body>
</html>
